// All context packs and their scenarios
// pro: true = requires Pro plan

export const PACKS = [
  {
    id: 'core_professional',
    label: 'Core Professional',
    icon: '⚡',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.08)',
    border: 'rgba(245,158,11,0.2)',
    scenarios: [
      { id: 'clean_professional_reply',      label: 'Clean Professional Reply' },
      { id: 'acknowledge_and_confirm',       label: 'Acknowledge & Confirm' },
      { id: 'neutral_follow_up',             label: 'Neutral Follow-Up' },
      { id: 'say_yes_simply',                label: 'Say Yes Simply' },
      { id: 'polite_decline',                label: 'Polite Decline' },
      { id: 'clarify_without_tension',       label: 'Clarify Without Tension' },
      { id: 'professional_apology',          label: 'Professional Apology' },
      { id: 'close_the_loop',                label: 'Close the Loop' },
      { id: 'acknowledge_delay',             label: 'Acknowledge Delay' },
      { id: 'neutral_reminder',              label: 'Neutral Reminder' },
      { id: 'confirm_next_steps',            label: 'Confirm Next Steps' },
      { id: 'soft_boundary',                 label: 'Soft Boundary' },
      { id: 'professional_thank_you',        label: 'Professional Thank You' },
      { id: 'minimal_response',              label: 'Minimal Response' },
      { id: 'calm_correction',               label: 'Calm Correction' },
      { id: 'professional_check_in',         label: 'Professional Check-In' },
      { id: 'neutral_agreement',             label: 'Neutral Agreement' },
      { id: 'professional_pause',            label: 'Professional Pause' },
      { id: 'confirm_availability',          label: 'Confirm Availability' },
      { id: 'close_with_authority',          label: 'Close with Authority' },
      { id: 'acknowledge_without_commit',    label: 'Acknowledge Without Commitment' },
      { id: 'soft_no_keep_door_open',        label: 'Soft No, Keep Door Open' },
      { id: 'confirm_understanding',         label: 'Confirm Understanding' },
      { id: 'redirect_conversation',         label: 'Redirect Conversation' },
      { id: 'neutral_delay_explanation',     label: 'Neutral Delay Explanation' },
      { id: 'minimal_professional_agreement',label: 'Minimal Professional Agreement' },
      { id: 'polite_re_engagement',          label: 'Polite Re-Engagement' },
      { id: 'end_with_professional_courtesy',label: 'End with Professional Courtesy' },
      { id: 'professional_deflection',       label: 'Professional Deflection' },
      { id: 'calm_acknowledgement_only',     label: 'Calm Acknowledgement Only' },
    ],
  },
  {
    id: 'sales',
    label: 'Sales',
    icon: '💼',
    color: 'var(--green)',
    bg: 'rgba(34,197,94,0.08)',
    border: 'rgba(34,197,94,0.2)',
    scenarios: [
      { id: 'first_sales_reply',         label: 'First Sales Reply' },
      { id: 'follow_up_after_silence',   label: 'Follow-Up After Silence' },
      { id: 'reschedule_call',           label: 'Reschedule Call' },
      { id: 'qualify_lead',              label: 'Qualify Lead' },
      { id: 'urgency_without_pressure',  label: 'Urgency Without Pressure' },
      { id: 'follow_up_after_call',      label: 'Follow-Up After Call' },
      { id: 'reignite_cold_lead',        label: 'Reignite Cold Lead' },
      { id: 'close_thread',              label: 'Close Thread' },
      { id: 'handle_price_objection',    label: 'Handle Price Objection' },
      { id: 'soft_close',                label: 'Soft Close' },
      { id: 'firm_close',                label: 'Firm Close' },
      { id: 'pushback_without_loss',     label: 'Pushback Without Loss' },
      { id: 'discount_refusal',          label: 'Discount Refusal' },
      { id: 'handle_let_me_think',       label: "Handle 'Let Me Think'" },
      { id: 'confirm_deal',              label: 'Confirm Deal' },
      { id: 'upsell_smoothly',           label: 'Upsell Smoothly' },
      { id: 'say_no_to_bad_fit',         label: 'Say No to Bad Fit' },
      { id: 'handle_comparison',         label: 'Handle Comparison' },
      { id: 'payment_nudge',             label: 'Payment Nudge' },
      { id: 'executive_sales_reply',     label: 'Executive Sales Reply' },
      { id: 'handle_too_busy',           label: "Handle 'Too Busy'" },
      { id: 'value_reframe',             label: 'Value Reframe' },
      { id: 'soft_deadline_reminder',    label: 'Soft Deadline Reminder' },
      { id: 'decision_window_close',     label: 'Decision Window Close' },
      { id: 'reconfirm_interest',        label: 'Reconfirm Interest' },
      { id: 'stakeholder_delay_reply',   label: 'Stakeholder Delay Reply', pro: true },
      { id: 'procurement_pushback',      label: 'Procurement Pushback', pro: true },
      { id: 'walk_away_calmly',          label: 'Walk Away Calmly', pro: true },
      { id: 'late_payment_firm_nudge',   label: 'Late Payment Firm Nudge', pro: true },
      { id: 'final_payment_warning',     label: 'Final Payment Warning', pro: true },
    ],
  },
  {
    id: 'customer_support',
    label: 'Customer Support',
    icon: '🎧',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.2)',
    scenarios: [
      { id: 'acknowledge_complaint',     label: 'Acknowledge Complaint' },
      { id: 'apology_without_fault',     label: 'Apology Without Fault' },
      { id: 'delay_explanation',         label: 'Delay Explanation' },
      { id: 'clarify_issue',             label: 'Clarify Issue' },
      { id: 'close_ticket',              label: 'Close Ticket' },
      { id: 'service_outage_notice',     label: 'Service Outage Notice' },
      { id: 'delay_apology',             label: 'Delay Apology' },
      { id: 'minimal_closure',           label: 'Minimal Closure' },
      { id: 'resolution_update',         label: 'Resolution Update' },
      { id: 'firm_policy_reply',         label: 'Firm Policy Reply' },
      { id: 'refund_response',           label: 'Refund Response' },
      { id: 'angry_customer_reply',      label: 'Angry Customer Reply' },
      { id: 'follow_up_satisfaction',    label: 'Follow-Up Satisfaction' },
      { id: 'say_no_politely',           label: 'Say No Politely' },
      { id: 'policy_reminder',           label: 'Policy Reminder' },
      { id: 'escalation_notice',         label: 'Escalation Notice' },
      { id: 'compensation_offer',        label: 'Compensation Offer' },
      { id: 'account_warning',           label: 'Account Warning' },
      { id: 'final_response',            label: 'Final Response' },
      { id: 'acknowledge_feedback',      label: 'Acknowledge Feedback' },
      { id: 'angry_review_reply',        label: 'Angry Review Reply' },
      { id: 'false_review_reply',        label: 'False Review Reply' },
      { id: 'refund_demand_review',      label: 'Refund Demand Review' },
      { id: 'neutral_review_thanks',     label: 'Neutral Review Thanks' },
      { id: 'staff_complaint_review',    label: 'Staff Complaint Review' },
      { id: 'delay_review_reply',        label: 'Delay Review Reply' },
      { id: 'private_follow_up_request', label: 'Private Follow-Up Request' },
      { id: 'policy_denial_review',      label: 'Policy Denial Review' },
      { id: 'final_public_reply',        label: 'Final Public Reply' },
      { id: 'chargeback_warning',        label: 'Chargeback Warning' },
    ],
  },
  {
    id: 'work',
    label: 'Work / Corporate',
    icon: '🏢',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
    scenarios: [
      { id: 'professional_first_reply',  label: 'Professional First Reply' },
      { id: 'meeting_confirmation',      label: 'Meeting Confirmation' },
      { id: 'reschedule_respectfully',   label: 'Reschedule Respectfully' },
      { id: 'follow_up_no_reply',        label: 'Follow-Up After No Reply' },
      { id: 'set_scope_boundary',        label: 'Set Scope Boundary' },
      { id: 'disagree_professionally',   label: 'Disagree Professionally' },
      { id: 'respond_to_criticism',      label: 'Respond to Criticism' },
      { id: 'status_update',             label: 'Status Update' },
      { id: 'request_extension',         label: 'Request Extension' },
      { id: 'interview_thank_you',       label: 'Interview Thank You' },
      { id: 'salary_response',           label: 'Salary Response' },
      { id: 'decline_offer',             label: 'Decline Offer' },
      { id: 'apology_work_safe',         label: 'Apology (Work-Safe)' },
      { id: 'executive_reply',           label: 'Executive Reply' },
      { id: 'clarify_deliverables',      label: 'Clarify Deliverables' },
      { id: 'escalate_issue',            label: 'Escalate Issue' },
      { id: 'end_thread_cleanly',        label: 'End Thread Cleanly' },
      { id: 'confirm_decision',          label: 'Confirm Decision' },
      { id: 'work_check_in',             label: 'Work Check-In' },
      { id: 'protect_time',              label: 'Protect Time' },
      { id: 'respond_to_pushback',       label: 'Respond to Pushback' },
      { id: 'clarify_role_confusion',    label: 'Clarify Role Confusion' },
      { id: 'coaching_feedback',         label: 'Coaching Feedback' },
      { id: 'professional_exit_reply',   label: 'Professional Exit Reply' },
      { id: 'attendance_warning',        label: 'Attendance Warning', pro: true },
      { id: 'performance_concern',       label: 'Performance Concern', pro: true },
      { id: 'boundary_after_hours',      label: 'Boundary After Hours', pro: true },
      { id: 'document_conversation',     label: 'Document Conversation', pro: true },
      { id: 'policy_reminder',           label: 'Policy Reminder', pro: true },
      { id: 'written_warning_tone',      label: 'Written Warning Tone', pro: true },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    icon: '🤝',
    color: 'var(--blue)',
    bg: 'rgba(56,189,248,0.08)',
    border: 'rgba(56,189,248,0.2)',
    scenarios: [
      { id: 'first_reply',               label: 'First Reply' },
      { id: 'set_a_boundary',            label: 'Set a Boundary' },
      { id: 'respond_to_conflict',       label: 'Respond to Conflict' },
      { id: 'apologize_sincerely',       label: 'Apologize Sincerely' },
      { id: 'express_feelings',          label: 'Express Feelings Clearly' },
      { id: 'decline_invitation',        label: 'Decline Invitation' },
      { id: 'check_in_on_someone',       label: 'Check In on Someone' },
      { id: 'end_a_friendship',          label: 'End a Friendship' },
      { id: 'handle_passive_aggression', label: 'Handle Passive Aggression' },
      { id: 'reconnect_after_distance',  label: 'Reconnect After Distance' },
      { id: 'respond_to_criticism',      label: 'Respond to Criticism' },
      { id: 'clarify_misunderstanding',  label: 'Clarify Misunderstanding' },
      { id: 'support_someone',           label: 'Support Someone' },
      { id: 'say_no_kindly',             label: 'Say No Kindly' },
      { id: 'navigate_awkwardness',      label: 'Navigate Awkwardness' },
      { id: 'end_a_conversation',        label: 'End a Conversation' },
      { id: 'handle_an_oversharer',      label: 'Handle an Oversharer' },
      { id: 'respond_to_guilt_trip',     label: 'Respond to Guilt Trip' },
      { id: 'reaffirm_a_boundary',       label: 'Reaffirm a Boundary' },
      { id: 'calm_a_situation',          label: 'Calm a Situation' },
    ],
  },
  {
    id: 'dating',
    label: 'Dating',
    icon: '💬',
    color: '#f472b6',
    bg: 'rgba(244,114,182,0.08)',
    border: 'rgba(244,114,182,0.2)',
    scenarios: [
      { id: 'first_reply',                   label: 'First Reply' },
      { id: 'flirty_but_safe',               label: 'Flirty But Safe' },
      { id: 'slow_things_down',              label: 'Slow Things Down' },
      { id: 'clarify_intentions',            label: 'Clarify Intentions' },
      { id: 'respond_to_mixed_signals',      label: 'Respond to Mixed Signals' },
      { id: 'set_boundary',                  label: 'Set Boundary' },
      { id: 'reignite_conversation',         label: 'Reignite Conversation' },
      { id: 'decline_politely',              label: 'Decline Politely' },
      { id: 'handle_ghosting',               label: 'Handle Ghosting' },
      { id: 'express_interest',              label: 'Express Interest' },
      { id: 'address_tension',               label: 'Address Tension' },
      { id: 'end_things_kindly',             label: 'End Things Kindly' },
      { id: 'check_in_after_date',           label: 'Check-In After Date' },
      { id: 'pause_communication',           label: 'Pause Communication' },
      { id: 'respond_to_over_texting',       label: 'Respond to Over-Texting' },
      { id: 'handle_emotional_message',      label: 'Handle Emotional Message' },
      { id: 'reaffirm_boundary',             label: 'Reaffirm Boundary' },
      { id: 'confirm_plans',                 label: 'Confirm Plans' },
      { id: 'minimal_confident_reply',       label: 'Minimal Confident Reply' },
      { id: 'graceful_silence_response',     label: 'Graceful Silence Response' },
      { id: 'respond_to_late_reply',         label: 'Respond to Late Reply' },
      { id: 'light_reset_after_awkwardness', label: 'Light Reset After Awkwardness' },
      { id: 'address_mismatch',              label: 'Address Mismatch' },
      { id: 'express_discomfort',            label: 'Express Discomfort' },
      { id: 'decline_second_date',           label: 'Decline Second Date' },
      { id: 'handle_emotional_overshare',    label: 'Handle Emotional Overshare' },
      { id: 'reconfirm_interest_level',      label: 'Reconfirm Interest Level' },
      { id: 'pause_romantic_momentum',       label: 'Pause Romantic Momentum' },
      { id: 'maintain_frame_reply',          label: 'Maintain Frame Reply' },
      { id: 'graceful_final_message',        label: 'Graceful Final Message' },
    ],
  },
]


export const PACK_MAP = Object.fromEntries(PACKS.map(p => [p.id, p]))
