export const TOOL_CONFIGS = {
  'reply-generator': {
    id: 'reply-generator',
    label: 'Reply Generator',
    tagline: 'Generate calm, strategic replies in seconds.',
    description: 'Paste any message and get 4 tailored reply options — Balanced, Firm, Warm, and Delay — each crafted for your specific context.',
    color: 'var(--green)',
    bg: 'rgba(34,197,94,0.08)',
    border: 'rgba(34,197,94,0.2)',
    backendRoute: 'replies',
    fields: [
      {
        id: 'message',
        label: 'Message received',
        type: 'textarea',
        placeholder: 'Paste the message you received…',
        required: true,
        rows: 5,
      },

      {
        id: 'context',
        label: 'Context chips',
        type: 'chips',
        placeholder: 'Or type your own context…',
        maxSelect: 2,
        chips: [
          'This is my boss',
          "We've had tension before",
          'This is a client',
          "We're in a negotiation",
          'This is a close friend',
          'First time this happened',
          "They've said this before",
          'High-stakes relationship',
          'I need to stay calm',
          'I want to end the conversation',
          'Urgent',
          'Sensitive',
        ],
      },
      {
        id: 'audience',
        label: 'Who sent this?',
        type: 'select',
        options: ['Boss', 'Colleague', 'Client', 'Direct report', 'Partner', 'Friend', 'Stranger', 'Recruiter'],
      },
      {
        id: 'medium',
        label: 'Reply medium',
        type: 'select',
        options: ['Email', 'SMS / Text', 'WhatsApp', 'LinkedIn', 'Slack', 'In person'],
      },
      {
        id: 'length',
        label: 'Preferred length',
        type: 'select',
        options: ['Very short (1-2 sentences)', 'Short (3-4 sentences)', 'Medium (1 paragraph)', 'Long (detailed)'],
      },
      {
        id: 'tone_pref',
        label: 'Your tone',
        type: 'select',
        options: ['Professional', 'Friendly', 'Direct', 'Empathetic', 'Formal'],
      },
      {
        id: 'pack_scenario',
        label: 'Context Pack & Scenario',
        type: 'pack-modal',
        placeholder: 'Choose a pack and scenario…',
      },
      {
        id: 'goal',
        label: 'Your goal',
        type: 'select',
        options: [
          'De-escalate and set a clear timeline',
          'Assert my position',
          'Build rapport',
          'Set a boundary',
          'Request more time',
          'Decline gracefully',
          'Escalate urgency',
          'Close the conversation',
        ],
      },
    ],
    outputVariants: ['Balanced', 'Firm', 'Warm', 'Delay'],
    buildPrompt: (f) => `You are an expert communication coach. Analyze this message and generate 4 reply options.\n\nMessage received: "${f.message}"\n${f.thread_context ? `Thread context: ${f.thread_context}` : ''}\n${f.context ? `Context: ${f.context}` : ''}\nAudience: ${f.audience || 'Boss'}\nReply medium: ${f.medium || 'Email'}\nPreferred length: ${f.length || 'Short (3-4 sentences)'}\nTone preference: ${f.tone_pref || 'Professional'}\nGoal: ${f.goal || 'De-escalate and set a clear timeline'}\n\nReturn ONLY valid JSON:\n{\n  "tone": "<detected tone in 2 words>",\n  "risk": "<risk label>",\n  "intent": "<sender intent>",\n  "strategy": "<one sentence recommended strategy>",\n  "risk_detail": "<2 sentence explanation of the risk if not handled well>",\n  "replies": {\n    "Balanced": "<reply>",\n    "Firm": "<reply>",\n    "Warm": "<reply>",\n    "Delay": "<reply>"\n  },\n  "tip": "<one practical communication tip for this situation>"\n}`,
  },

  'tone-checker': {
    id: 'tone-checker',
    label: 'Tone Checker',
    tagline: 'Understand the emotional charge of any message.',
    description: 'Get a deep breakdown of tone, subtext, emotional intent, and hidden signals in any message before you respond.',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
    backendRoute: 'tone',
    fields: [
      {
        id: 'message',
        label: 'Message to analyze',
        type: 'textarea',
        placeholder: 'Paste any message here…',
        required: true,
        rows: 5,
      },
      {
        id: 'relationship',
        label: 'Your relationship',
        type: 'select',
        options: ['Colleague', 'Boss / Manager', 'Direct report', 'Client', 'Partner / Spouse', 'Friend', 'Stranger'],
      },
      {
        id: 'history',
        label: 'Any prior tension?',
        type: 'select',
        options: ['No history', 'Minor tension', 'Ongoing conflict', 'Recent argument', 'Reconciling'],
      },

    ],
    outputVariants: null,
    buildPrompt: (f) => `You are an expert in emotional communication and subtext analysis. Deeply analyze this message.\n\nMessage: "${f.message}"\nRelationship to sender: ${f.relationship || 'Colleague'}\nPrior tension: ${f.history || 'No history'}\n${f.context ? `Context: ${f.context}` : ''}\n\nReturn ONLY valid JSON:\n{\n  "primary_tone": "<main tone in 2-3 words>",\n  "secondary_tone": "<underlying tone in 2-3 words>",\n  "intent": "<what the sender actually wants>",\n  "subtext": "<what they are NOT saying but implying>",\n  "risk_level": "<Low / Medium / High>",\n  "risk_reason": "<why this risk level>",\n  "emotional_signals": ["<signal 1>", "<signal 2>", "<signal 3>"],\n  "what_not_to_do": "<biggest mistake to avoid when replying>",\n  "recommended_approach": "<how to approach the reply>",\n  "urgency": "<Low / Medium / High>",\n  "urgency_reason": "<why>"\n}`,
  },

  'boundary-builder': {
    id: 'boundary-builder',
    label: 'Boundary Builder',
    tagline: 'Set firm, respectful limits without conflict.',
    description: 'Turn pushback, overreach, or pressure into calm, clear boundaries — without burning the relationship.',
    color: 'var(--green)',
    bg: 'rgba(34,197,94,0.08)',
    border: 'rgba(34,197,94,0.2)',
    backendRoute: 'boundary',
    fields: [
      { id: 'what_is_happening',    label: 'What is happening?',         type: 'textarea', placeholder: 'Describe the situation or paste the message…', required: true, rows: 4 },
      { id: 'what_boundary_needed', label: 'What boundary do you need?', type: 'textarea', placeholder: 'e.g. I need them to stop contacting me after hours…', required: true, rows: 3 },
      { id: 'relationship',         label: 'Your relationship',          type: 'select',   options: ['colleague', 'boss', 'client', 'family', 'friend', 'partner', 'acquaintance'] },
      { id: 'relationship_stakes',  label: 'Relationship stakes',        type: 'select',   options: ['high', 'medium', 'low'] },
      { id: 'said_before',          label: 'Have you said this before?', type: 'select',   options: ['first_time', 'said_once', 'said_multiple_times'] },
      { id: 'medium',               label: 'Reply medium',               type: 'select',   options: ['Email', 'SMS / Text', 'WhatsApp', 'LinkedIn', 'Slack', 'In person'] },
    ],
    outputVariants: ['Firm', 'Gentle', 'Final'],
    buildPrompt: (f) => '',
  },

  'negotiation-reply': {
    id: 'negotiation-reply',
    label: 'Negotiation Reply',
    tagline: 'Hold your position under pressure.',
    description: 'Get strategically crafted replies for salary negotiations, pricing pushback, contract terms, and high-stakes deals.',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
    backendRoute: 'negotiation',
    fields: [
      { id: 'their_message',         label: 'Their message / offer',        type: 'textarea', placeholder: 'Paste what they said or offered…', required: true, rows: 4 },
      { id: 'your_position',         label: 'Your position / counter-offer', type: 'textarea', placeholder: 'What do you actually want? e.g. $95k, not $85k…', rows: 2 },
      { id: 'negotiation_context',   label: 'Negotiation context',          type: 'select',   options: ['salary_negotiation', 'pricing_deal', 'contract_terms', 'raise_request', 'partnership_deal', 'freelance_rate', 'other'] },
      { id: 'leverage',              label: 'Your leverage',                type: 'select',   options: ['strong', 'moderate', 'weak', 'unknown'] },
      { id: 'style',                 label: 'Negotiation style',            type: 'select',   options: ['collaborative', 'competitive', 'principled', 'relationship_first'] },
      { id: 'medium',                label: 'Reply medium',                 type: 'select',   options: ['Email', 'SMS / Text', 'WhatsApp', 'LinkedIn', 'Slack', 'In person'] },
    ],
    outputVariants: ['Hold Firm', 'Counter', 'Collaborative'],
    buildPrompt: (f) => '',
  },

  'follow-up-writer': {
    id: 'follow-up-writer',
    label: 'Follow-Up Writer',
    tagline: 'Follow-ups that actually get responses.',
    description: 'Write follow-up messages that are persistent without being pushy — for job applications, sales, invoices, and more.',
    color: 'var(--blue)',
    bg: 'rgba(56,189,248,0.08)',
    border: 'rgba(56,189,248,0.2)',
    backendRoute: 'followup',
    fields: [
      { id: 'context',          label: 'What are you following up on?', type: 'textarea', placeholder: "e.g. I applied for a senior developer role at Acme Corp two weeks ago.", required: true, rows: 3 },
      { id: 'last_contact',     label: 'Last contact',                  type: 'select',   options: ['1_2_days', '3_5_days', '1_week', '2_weeks', '1_month', 'over_a_month'] },
      { id: 'follow_up_type',   label: 'Follow-up type',                type: 'select',   options: ['job_application', 'sales_proposal', 'invoice_payment', 'meeting_request', 'project_update', 'personal', 'other'] },
      { id: 'follow_up_number', label: 'Which follow-up is this?',      type: 'select',   options: ['first_follow_up', 'second_follow_up', 'third_follow_up', 'post_meeting'] },
      { id: 'preferred_tone',   label: 'Preferred tone',                type: 'select',   options: ['professional', 'friendly', 'urgent', 'brief'] },
      { id: 'medium',           label: 'Reply medium',                  type: 'select',   options: ['Email', 'SMS / Text', 'WhatsApp', 'LinkedIn', 'Slack'] },
    ],
    outputVariants: ['Standard', 'Shorter'],
    buildPrompt: (f) => '',
  },

  'difficult-email': {
    id: 'difficult-email',
    label: 'Difficult Email',
    tagline: 'Rewrite sensitive workplace emails safely.',
    description: 'Turn tricky, sensitive, or high-stakes messages into two polished versions — one safe, one direct.',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.08)',
    border: 'rgba(245,158,11,0.2)',
    backendRoute: 'difficultEmail',
    fields: [
      { id: 'what_to_communicate', label: 'What do you need to communicate?', type: 'textarea', placeholder: 'e.g. I need to tell my client we cannot deliver the project on the agreed date.', required: true, rows: 4 },
      { id: 'draft',               label: 'Your draft (optional)',             type: 'textarea', placeholder: 'Paste your draft if you have one…', required: false, rows: 3 },
      { id: 'situation',           label: 'Situation type',                    type: 'select',   options: ['giving_bad_news', 'declining_request', 'addressing_conflict', 'delivering_feedback', 'apologizing', 'setting_expectations', 'other'] },
      { id: 'relationship',        label: 'Recipient relationship',            type: 'select',   options: ['client', 'boss', 'colleague', 'direct_report', 'partner', 'vendor', 'other'] },
      { id: 'sensitivity',         label: 'Sensitivity level',                 type: 'select',   options: ['high', 'medium', 'low'] },
    ],
    outputVariants: ['Safe', 'Direct'],
    buildPrompt: (f) => '',
  },

  'intent-detector': {
    id: 'intent-detector',
    label: 'Intent Detector',
    tagline: 'Understand the hidden meaning behind any message.',
    description: 'Decode surface meaning, real intent, emotional state, and warning signals in any message.',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.2)',
    backendRoute: 'intent',
    fields: [
      { id: 'message',      label: 'Message to decode',  type: 'textarea', placeholder: 'Paste the message…', required: true, rows: 5 },
      { id: 'relationship', label: 'Your relationship',  type: 'select',   options: ['colleague', 'boss', 'client', 'partner', 'friend', 'stranger', 'direct_report'] },
      { id: 'channel',      label: 'Channel',            type: 'select',   options: ['email', 'slack', 'whatsapp', 'sms', 'linkedin', 'in_person'] },
      { id: 'background',   label: 'Background context', type: 'textarea', placeholder: 'Any context that might affect the intent… (optional)', required: false, rows: 2 },
    ],
    outputVariants: null,
    buildPrompt: (f) => '',
  },
}

export const TOOL_SLUGS = Object.keys(TOOL_CONFIGS)
